directories:
  output: release
  buildResources: build
appId: com.slimming-ds.app
productName: SlimmingCheckin
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: 减重追踪
npmRebuild: false
files: []
electronVersion: 31.7.7
